-- =============================================================================
-- RLS (Row Level Security) + app_admin for Apna Hunar / Kshatr
-- Run in Supabase SQL Editor. Ensures only authorized access per role.
-- =============================================================================

-- 1. Admin registry: users in this table get full admin access via RLS
CREATE TABLE IF NOT EXISTS public.app_admin (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id)
);

ALTER TABLE public.app_admin ENABLE ROW LEVEL SECURITY;

-- Only existing admins (or service_role) can manage app_admin
CREATE POLICY "app_admin_select_own" ON public.app_admin
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "app_admin_all_service_role" ON public.app_admin
  FOR ALL USING (auth.jwt()->>'role' = 'service_role');

-- 2. categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "categories_select_anon_active" ON public.categories
  FOR SELECT USING (is_active = true);

CREATE POLICY "categories_admin_all" ON public.categories
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- 3. services
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

CREATE POLICY "services_select_anon_active" ON public.services
  FOR SELECT USING (is_active = true);

CREATE POLICY "services_admin_all" ON public.services
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- 4. spotlight_offers
ALTER TABLE public.spotlight_offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "spotlight_offers_select_anon_active" ON public.spotlight_offers
  FOR SELECT USING (is_active = true);

CREATE POLICY "spotlight_offers_admin_all" ON public.spotlight_offers
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- 5. admin_settings (anon read for app config; admin write)
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_settings_select_anon" ON public.admin_settings
  FOR SELECT USING (true);

CREATE POLICY "admin_settings_admin_all" ON public.admin_settings
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- 6. bookings
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "bookings_insert_customer" ON public.bookings
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "bookings_select_customer" ON public.bookings
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "bookings_select_expert" ON public.bookings
  FOR SELECT USING (
    expert_id IN (SELECT id FROM public.experts WHERE user_id = auth.uid())
  );

CREATE POLICY "bookings_update_expert" ON public.bookings
  FOR UPDATE USING (
    expert_id IN (SELECT id FROM public.experts WHERE user_id = auth.uid())
  );

CREATE POLICY "bookings_admin_all" ON public.bookings
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- 7. user_addresses
ALTER TABLE public.user_addresses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user_addresses_own" ON public.user_addresses
  FOR ALL USING (auth.uid() = user_id);

-- 8. experts
ALTER TABLE public.experts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "experts_select_own" ON public.experts
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "experts_update_own" ON public.experts
  FOR UPDATE USING (user_id = auth.uid());

CREATE POLICY "experts_admin_all" ON public.experts
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- Experts insert: allow on sign-up (RegisterExpert) when user_id = auth.uid()
CREATE POLICY "experts_insert_own" ON public.experts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 9. area_heads
ALTER TABLE public.area_heads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "area_heads_select_own" ON public.area_heads
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "area_heads_admin_all" ON public.area_heads
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- Area head insert: only admin (from AreaHeadManager)
CREATE POLICY "area_heads_insert_admin" ON public.area_heads
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- 10. legal_pages
ALTER TABLE public.legal_pages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "legal_pages_select_anon" ON public.legal_pages
  FOR SELECT USING (true);

CREATE POLICY "legal_pages_admin_all" ON public.legal_pages
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- 11. customers (CRM - admin only)
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "customers_admin_all" ON public.customers
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- 12. profiles (user own)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles_select_own" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "profiles_insert_own" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- 13. wallet_transactions
ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "wallet_transactions_select_expert" ON public.wallet_transactions
  FOR SELECT USING (
    user_type = 'expert' AND user_id IN (SELECT id FROM public.experts WHERE user_id = auth.uid())
  );

CREATE POLICY "wallet_transactions_select_area_head" ON public.wallet_transactions
  FOR SELECT USING (
    user_type = 'area_head' AND user_id IN (SELECT id FROM public.area_heads WHERE user_id = auth.uid())
  );

CREATE POLICY "wallet_transactions_admin_all" ON public.wallet_transactions
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- Experts/PartnerApp insert wallet_transactions (on job complete)
CREATE POLICY "wallet_transactions_insert_expert" ON public.wallet_transactions
  FOR INSERT WITH CHECK (
    user_type = 'expert' AND user_id IN (SELECT id FROM public.experts WHERE user_id = auth.uid())
  );

-- 14. withdrawal_requests
ALTER TABLE public.withdrawal_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "withdrawal_requests_select_expert" ON public.withdrawal_requests
  FOR SELECT USING (
    user_id IN (SELECT id FROM public.experts WHERE user_id = auth.uid())
  );

CREATE POLICY "withdrawal_requests_select_area_head" ON public.withdrawal_requests
  FOR SELECT USING (
    user_id IN (SELECT id FROM public.area_heads WHERE user_id = auth.uid())
  );

CREATE POLICY "withdrawal_requests_insert_expert" ON public.withdrawal_requests
  FOR INSERT WITH CHECK (
    user_id IN (SELECT id FROM public.experts WHERE user_id = auth.uid())
  );

CREATE POLICY "withdrawal_requests_admin_all" ON public.withdrawal_requests
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
  );

-- =============================================================================
-- NOTES
-- =============================================================================
-- 1. DeepakHQ uses Supabase Auth. Add first admin via Dashboard SQL (as service_role):
--    INSERT INTO app_admin (user_id) SELECT id FROM auth.users WHERE email = 'your-admin@example.com' LIMIT 1;
-- 2. If a table does not exist yet, this migration may fail on that section;
--    create the table first or comment out that section.
-- 3. service_role bypasses RLS; anon key is restricted by these policies.
