-- =============================================================================
-- error_logs: Production error monitoring (alternative to Sentry)
-- Client can log critical crashes for debugging. RLS allows anon INSERT.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.error_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  message text NOT NULL,
  error_stack text,
  error_message text,
  path text,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  user_agent text,
  severity text DEFAULT 'error' CHECK (severity IN ('error', 'critical', 'warning'))
);

-- Index for querying recent errors
CREATE INDEX IF NOT EXISTS idx_error_logs_created_at ON public.error_logs (created_at DESC);

ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;

-- Allow anon/client to INSERT (for production error reporting)
CREATE POLICY "error_logs_insert_anon" ON public.error_logs
  FOR INSERT WITH CHECK (true);

-- Only admins (or service_role) can SELECT/read logs
CREATE POLICY "error_logs_select_admin" ON public.error_logs
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.app_admin WHERE user_id = auth.uid())
    OR (auth.jwt()->>'role' = 'service_role')
  );
