ALTER TABLE experts ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE experts ADD COLUMN IF NOT EXISTS kyc_status TEXT DEFAULT 'pending';
ALTER TABLE experts ADD COLUMN IF NOT EXISTS average_rating NUMERIC DEFAULT 0;
ALTER TABLE experts ADD COLUMN IF NOT EXISTS total_reviews INTEGER DEFAULT 0;
